# Generated by Django 4.2 on 2023-05-03 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='telegram_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
